lenra-io/dofigen

README.md
Add documentation on how Dofigen uses Buildkit optimizations
=> docs: Explain the Buildkit optimizations

README.md
=> docs: Add crates.io badge to README.md (#18)

.github/workflows/build_ci.yml
#27  
Run the publish job only if semantic release find a next version
=> ci: Publish if next version

Cargo.lock, src/bin/main.rs, src/lib.rs
Expose the error module and upgrade dependencies
=> feat: Expose errors module

.github/workflows/build_ci.yml, Cargo.lock
This PR just change some steps in the workflow release file that was defined here by some that use the reusable workflow we already have defined in our github-action repository. Spatially for Semantic-release steps.
=> ci: upgrade ci to our github-actions workflows.

.github/workflows/build_ci.yml
=> ci: add github release in CI

.github/workflows/build_ci.yml, src/bin/main.rs, src/runners.rs, src/stages.rs
=> test: Add some unit tests

README.md, src/lib.rs, src/runners.rs, src/stages.rs, src/structs.rs
Closes #202 
The old field names are working since I created corresponding aliases.
=> refactor!: Remove deprecated elements and rename fields to match Dockerfile commands

README.md, src/bin/commands/generate.rs
Refactor the generate command to have a better option management.
Closes #195
=> feat!: Improve the gen command options

.github/release.sh, .github/workflows/build_ci.yml
=> ci: Generate Docker image & do not compress artifacts

src/bin/commands/update.rs
The `--dry-run` flag of the update subcommand displays the updated lockfile.
For now this is not really useful, IMO the `Add ressource ...` logs are explicite enough.
Run `dofigen update --dry-run`
=> fix: Do not display lockfile on update --dry-run

src/deserialize.rs
Closes #274 
See the issue.
I added a corresponding unit test for this case. Just run `cargo test`
=> fix: Accept one or many in vec patch elements

docs/dofigen.schema.json, dofigen.lock, dofigen.yml, src/dofigen_struct.rs, src/generator.rs, tests/lib_test.rs
Closes #250 
See the issue
As YAML does not differentiate `null` and `undefined`, the arg type is HashMap<String, String>.
To define an arg without value just define it with an empty string.
Empty string won't be a possible value in the generated Dockerfile, but I don't see any case where it would be needed...
Add an `arg` field in stage stage of the Dofigen file.
The generated Dockerfile should contain the corresponding `ARG` command.
=> feat: Manage stage ARG

docs/struct.md, dofigen.yml, src/dofigen_struct.rs, src/from_str.rs, src/generator.rs, src/lock.rs
=> fix: Cache struct from field and add struct documentation

docs/dofigen.schema.json, docs/struct.md, src/deserialize.rs, src/dockerfile_struct.rs, src/dofigen_struct.rs, src/generator.rs, tests/lib_test.rs, tests/regression_test.rs
Also renamed an enum variant
Closes #281 
Allow the use of integer for chmod value.
Creation of a specific deserialize function.
Unit tests have been added, so just run `cargo test`
You also can add a `chmod` field in a copy item with a int value.
=> feat: Permissive chmod

Cargo.toml, Dockerfile, dofigen.lock, dofigen.yml
Closes #300 
<sub><a href="https://huly.app/guest/lenra?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJhNTI5N2U3Y2M1YTc4NTQyODg1ZGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVibmVzcXdpLWxlbnJhLTY2YzQ1NjEwLWEwZmY2MDljODEtYzQyZjYxIn0.sP7dKHu8ssUaWEydjo0MK6d5XpVTn9vPOTbj5raXomI">Huly&reg;: <b>DOFIG-298</b></a></sub>
=> fix(docker): Docker entrypoint and optimize CLI size

Cargo.lock, Cargo.toml, README.md, dofigen.lock, dofigen.yml, src/bin/commands/effective.rs, src/bin/commands/generate.rs, src/bin/commands/mod.rs, src/bin/commands/update.rs, src/bin/main.rs, src/context.rs, src/dofigen_struct.rs, src/errors.rs, src/generator.rs, src/lib.rs, tests/cli_test.rs, tests/lib_test.rs
Closes #26
Creation of a linter (`LintSession`) that analyze the Dofigen configuration to report problems to the user.
The problems (`LintMessage`) are displayed in the `generate` sub-command and if there is at least one with the level `Error`, the command fails.
The cache checking corresponding message has the level `Error`.
I added corresponding unit tests.
To try it on a Dofigen config use the next command:
```bash
echo 'builders:
test:
run:
- echo "Hello, world!"
cache:
- /cache/path
copy:
- fromBuilder: test
source: /cache/path/file.txt
target: file.txt' | cargo run --  gen -f - -o -
```
<sub><a href="https://huly.app/guest/lenra?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM0ZTEzNmU3Y2M1YTc4NTQyYzI5NGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIn …
=> feat: Fail on cache artifact use

Cargo.lock, Cargo.toml
Closes #308 
Removed the reqwest default features to use the `rustls-tls` one.
- download the linux x86_64 binary from the Github action of the current branche or build the dofigen binary for the `x86_64-unknown-linux-musl` target locally
- copy the generated binary to the next path of the project `builds/linux/amd64/dofigen`
- Build the Docker image: `docker build -t dofigen:local .`
- Use the built image in a project with dependencies: `docker run --rm -it -v $(pwd):/app dofigen:local gen`
<sub><a href="https://huly.app/guest/lenra?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNkMTBiOWU3Y2M1YTc4NTQyZTMwNjciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVibmVzcXdpLWxlbnJhLTY2YzQ1NjEwLWEwZmY2MDljODEtYzQyZjYxIn0.mbnDuFYQqWedTzkAcCGKg …
=> fix: TLS error in Docker image from scratch

.github/homebrew.rb, .github/workflows/build_ci.yml, Cargo.lock, Cargo.toml, README.md
Closes #209 
The main purpose of this PR is to generate latest homebrew configuration file during Dofigen releases (not pre-releases) and update it on the [Lenra's homebrew repo](https://github.com/lenra-io/homebrew-tools).
Homebrew does not manage pre-releases and I'm not sure that is useful, so we only do it on main branch.
It's not easy... We will need to wait for the next release to see the result.
<sub><a href="https://huly.app/guest/lenra?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc3ZmViZWYxNDRmNTg1YWU1MjVmMTUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVibmVzcXdpLWxlbnJhLTY2YzQ1NjEwLWEwZmY2MDljODEtYzQyZjYxIn0.LCI-8emvIhsLWYbByMTwvcxLMR9FS6FZgCxn8iHTgew">Huly&reg;: <b>DOFIG-330</b></a></sub>
=> ci: Generate Homebrew configuration

Dockerfile, README.md, docs/dofigen.schema.json, docs/struct.md, dofigen.lock, dofigen.yml, src/deserialize.rs, src/dofigen_struct.rs, src/generator.rs
=> feat: Label management with nested map

Cargo.lock, Cargo.toml
Closes #322 
Changed the `reqwest` feature from `rustls-tls` to `rustls-tls-native-roots` as explained here: https://github.com/seanmonstar/reqwest/issues/2640
Create a local proxy with custom CA:
```bash
docker run --rm -it -v ~/.mitmproxy:/home/mitmproxy/.mitmproxy -p 8080:8080 mitmproxy/mitmproxy
```
In a new terminal (since the previous command is interactive) define the proxy:
```bash
export https_proxy=http://localhost:8080
```
Try to call a HTTPS url:
```bash
curl -v https://www.lenra.io
```
You should have a certificate error.
Run Dofigen to have the same kind of certificate error:
```bash
echo "fromImage: alpine" | cargo run -- gen -f - -o -
```
Define the custom CA file path in env var:
```bash
export SSL_CERT_FILE=~/.mitmproxy/mitmproxy-ca-cert.pem
```
You should run curl and …
=> fix: Add custom CA env var management

.github/workflows/build_ci.yml, .gitignore, Cargo.lock, dofigen.yml, src/dockerfile_struct.rs, src/generator.rs, src/lib.rs, tests/cases.rs
Closes #347 
None of the existing crates seems to manage comments and heredoc management at same time.
I had to use my own parser...
One interesting project is this one: https://crates.io/crates/dockerfile-parser-rs
But it does not manage formatting, some copy options (in labs) and heredocs yet.
I created an issue: https://github.com/slimreaper35/dockerfile-parser-rs/issues/3
For now, only managed by unit tests
=> feat: Parse Dockerfile content
